spring.application.name=petcare-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare_tracker
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
