spring.application.name=petcare-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare_tracker
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.mongodb.uri=mongodb://localhost:27017/petcare_tracker_logs
server.port=8080
