spring.application.name=petcare-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petcare_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/petcare_tracker_logs}
server.port=${SERVER_PORT:8080}
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
