services:
  postgres:
    image: postgres:17
    container_name: petcare-postgres
    environment:
      POSTGRES_DB: petcare_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./db/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d petcare_tracker"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:8
    container_name: petcare-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend/petcare-backend
      dockerfile: Dockerfile
    container_name: petcare-backend
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petcare_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/petcare_tracker_logs
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: petcare-prometheus
    depends_on:
      - backend
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.2.2
    container_name: petcare-grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  k6:
    image: grafana/k6:0.53.0
    container_name: petcare-k6
    profiles:
      - loadtest
    depends_on:
      - backend
    environment:
      BASE_URL: http://backend:8080
    volumes:
      - ./tests/k6:/scripts:ro
    entrypoint: ["k6"]

volumes:
  postgres_data:
  mongo_data:
  grafana_data:
