spring.application.name=pet-service
server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/petcare_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
