server:
  port: 8080

spring:
  application:
    name: petcare-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - AddRequestHeader=X-Gateway-Source, petcare-gateway

        - id: pet-service
          uri: http://pet-service:8082
          predicates:
            - Path=/api/pets/**, /api/health-records/**, /api/vaccines/**, /api/vaccine-records/**, /api/medications/**, /api/medication-schedules/**, /api/feeding-plans/**
          filters:
            - AddRequestHeader=X-Gateway-Source, petcare-gateway

        - id: care-service
          uri: http://care-service:8083
          predicates:
            - Path=/api/appointments/**, /api/reminders/**, /api/activity-logs/**
          filters:
            - AddRequestHeader=X-Gateway-Source, petcare-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
